
package ws.usuarios;

import jakarta.xml.ws.WebFault;


/**
 * This class was generated by the XML-WS Tools.
 * XML-WS Tools 4.0.0
 * Generated source version: 3.0
 * 
 */
@WebFault(name = "UsuarioRepetidoFault", targetNamespace = "http://publicar.ws/")
public class UsuarioRepetidoFault_Exception
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private UsuarioRepetidoFault faultInfo;

    /**
     * 
     * @param faultInfo
     * @param message
     */
    public UsuarioRepetidoFault_Exception(String message, UsuarioRepetidoFault faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param cause
     * @param faultInfo
     * @param message
     */
    public UsuarioRepetidoFault_Exception(String message, UsuarioRepetidoFault faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: ws.usuarios.UsuarioRepetidoFault
     */
    public UsuarioRepetidoFault getFaultInfo() {
        return faultInfo;
    }

}
