
package ws.usuarios;

import java.util.List;
import jakarta.jws.WebMethod;
import jakarta.jws.WebParam;
import jakarta.jws.WebResult;
import jakarta.jws.WebService;
import jakarta.xml.bind.annotation.XmlSeeAlso;
import jakarta.xml.ws.Action;
import jakarta.xml.ws.FaultAction;
import jakarta.xml.ws.RequestWrapper;
import jakarta.xml.ws.ResponseWrapper;


/**
 * This class was generated by the XML-WS Tools.
 * XML-WS Tools 4.0.0
 * Generated source version: 3.0
 * 
 */
@WebService(name = "UsuarioWs", targetNamespace = "http://publicar.ws/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface UsuarioWs {


    /**
     * 
     * @param ident
     * @param password
     * @return
     *     returns ws.usuarios.DataUsuario
     * @throws PasswordIncorrectaFault_Exception
     * @throws UsuarioNoExisteFault_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "login", targetNamespace = "http://publicar.ws/", className = "ws.usuarios.Login")
    @ResponseWrapper(localName = "loginResponse", targetNamespace = "http://publicar.ws/", className = "ws.usuarios.LoginResponse")
    @Action(input = "http://publicar.ws/UsuarioWs/loginRequest", output = "http://publicar.ws/UsuarioWs/loginResponse", fault = {
        @FaultAction(className = UsuarioNoExisteFault_Exception.class, value = "http://publicar.ws/UsuarioWs/login/Fault/UsuarioNoExisteFault"),
        @FaultAction(className = PasswordIncorrectaFault_Exception.class, value = "http://publicar.ws/UsuarioWs/login/Fault/PasswordIncorrectaFault")
    })
    public DataUsuario login(
        @WebParam(name = "ident", targetNamespace = "")
        String ident,
        @WebParam(name = "password", targetNamespace = "")
        String password)
        throws PasswordIncorrectaFault_Exception, UsuarioNoExisteFault_Exception
    ;

    /**
     * 
     * @param ident
     * @param password
     * @return
     *     returns ws.usuarios.DataUsuario
     * @throws PasswordIncorrectaFault_Exception
     * @throws UsuarioNoExisteFault_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "loginMovil", targetNamespace = "http://publicar.ws/", className = "ws.usuarios.LoginMovil")
    @ResponseWrapper(localName = "loginMovilResponse", targetNamespace = "http://publicar.ws/", className = "ws.usuarios.LoginMovilResponse")
    @Action(input = "http://publicar.ws/UsuarioWs/loginMovilRequest", output = "http://publicar.ws/UsuarioWs/loginMovilResponse", fault = {
        @FaultAction(className = UsuarioNoExisteFault_Exception.class, value = "http://publicar.ws/UsuarioWs/loginMovil/Fault/UsuarioNoExisteFault"),
        @FaultAction(className = PasswordIncorrectaFault_Exception.class, value = "http://publicar.ws/UsuarioWs/loginMovil/Fault/PasswordIncorrectaFault")
    })
    public DataUsuario loginMovil(
        @WebParam(name = "ident", targetNamespace = "")
        String ident,
        @WebParam(name = "password", targetNamespace = "")
        String password)
        throws PasswordIncorrectaFault_Exception, UsuarioNoExisteFault_Exception
    ;

    /**
     * 
     * @return
     *     returns java.util.List<ws.usuarios.DataUsuario>
     * @throws UsuarioNoExisteFault_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getAsistentes", targetNamespace = "http://publicar.ws/", className = "ws.usuarios.GetAsistentes")
    @ResponseWrapper(localName = "getAsistentesResponse", targetNamespace = "http://publicar.ws/", className = "ws.usuarios.GetAsistentesResponse")
    @Action(input = "http://publicar.ws/UsuarioWs/getAsistentesRequest", output = "http://publicar.ws/UsuarioWs/getAsistentesResponse", fault = {
        @FaultAction(className = UsuarioNoExisteFault_Exception.class, value = "http://publicar.ws/UsuarioWs/getAsistentes/Fault/UsuarioNoExisteFault")
    })
    public List<DataUsuario> getAsistentes()
        throws UsuarioNoExisteFault_Exception
    ;

    /**
     * 
     * @return
     *     returns java.util.List<ws.usuarios.DataUsuario>
     * @throws UsuarioNoExisteFault_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getUsuarios", targetNamespace = "http://publicar.ws/", className = "ws.usuarios.GetUsuarios")
    @ResponseWrapper(localName = "getUsuariosResponse", targetNamespace = "http://publicar.ws/", className = "ws.usuarios.GetUsuariosResponse")
    @Action(input = "http://publicar.ws/UsuarioWs/getUsuariosRequest", output = "http://publicar.ws/UsuarioWs/getUsuariosResponse", fault = {
        @FaultAction(className = UsuarioNoExisteFault_Exception.class, value = "http://publicar.ws/UsuarioWs/getUsuarios/Fault/UsuarioNoExisteFault")
    })
    public List<DataUsuario> getUsuarios()
        throws UsuarioNoExisteFault_Exception
    ;

    /**
     * 
     * @param nickname
     * @param nuevaPass
     */
    @WebMethod
    @RequestWrapper(localName = "cambiarContrasenia", targetNamespace = "http://publicar.ws/", className = "ws.usuarios.CambiarContrasenia")
    @ResponseWrapper(localName = "cambiarContraseniaResponse", targetNamespace = "http://publicar.ws/", className = "ws.usuarios.CambiarContraseniaResponse")
    @Action(input = "http://publicar.ws/UsuarioWs/cambiarContraseniaRequest", output = "http://publicar.ws/UsuarioWs/cambiarContraseniaResponse")
    public void cambiarContrasenia(
        @WebParam(name = "nickname", targetNamespace = "")
        String nickname,
        @WebParam(name = "nuevaPass", targetNamespace = "")
        String nuevaPass);

    /**
     * 
     * @param nickname
     * @return
     *     returns ws.usuarios.DataUsuario
     * @throws UsuarioNoExisteFault_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getAsistente", targetNamespace = "http://publicar.ws/", className = "ws.usuarios.GetAsistente")
    @ResponseWrapper(localName = "getAsistenteResponse", targetNamespace = "http://publicar.ws/", className = "ws.usuarios.GetAsistenteResponse")
    @Action(input = "http://publicar.ws/UsuarioWs/getAsistenteRequest", output = "http://publicar.ws/UsuarioWs/getAsistenteResponse", fault = {
        @FaultAction(className = UsuarioNoExisteFault_Exception.class, value = "http://publicar.ws/UsuarioWs/getAsistente/Fault/UsuarioNoExisteFault")
    })
    public DataUsuario getAsistente(
        @WebParam(name = "nickname", targetNamespace = "")
        String nickname)
        throws UsuarioNoExisteFault_Exception
    ;

    /**
     * 
     * @param apellido
     * @param descripcion
     * @param fechaNac
     * @param imagen
     * @param link
     * @param nickname
     * @param nombre
     * @throws UsuarioNoExisteFault_Exception
     */
    @WebMethod
    @RequestWrapper(localName = "modificarUsuario", targetNamespace = "http://publicar.ws/", className = "ws.usuarios.ModificarUsuario")
    @ResponseWrapper(localName = "modificarUsuarioResponse", targetNamespace = "http://publicar.ws/", className = "ws.usuarios.ModificarUsuarioResponse")
    @Action(input = "http://publicar.ws/UsuarioWs/modificarUsuarioRequest", output = "http://publicar.ws/UsuarioWs/modificarUsuarioResponse", fault = {
        @FaultAction(className = UsuarioNoExisteFault_Exception.class, value = "http://publicar.ws/UsuarioWs/modificarUsuario/Fault/UsuarioNoExisteFault")
    })
    public void modificarUsuario(
        @WebParam(name = "nickname", targetNamespace = "")
        String nickname,
        @WebParam(name = "nombre", targetNamespace = "")
        String nombre,
        @WebParam(name = "descripcion", targetNamespace = "")
        String descripcion,
        @WebParam(name = "imagen", targetNamespace = "")
        String imagen,
        @WebParam(name = "link", targetNamespace = "")
        String link,
        @WebParam(name = "apellido", targetNamespace = "")
        String apellido,
        @WebParam(name = "fechaNac", targetNamespace = "")
        String fechaNac)
        throws UsuarioNoExisteFault_Exception
    ;

    /**
     * 
     * @param nickname
     * @return
     *     returns ws.usuarios.DataUsuario
     * @throws UsuarioNoExisteFault_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "verInfoUsuario", targetNamespace = "http://publicar.ws/", className = "ws.usuarios.VerInfoUsuario")
    @ResponseWrapper(localName = "verInfoUsuarioResponse", targetNamespace = "http://publicar.ws/", className = "ws.usuarios.VerInfoUsuarioResponse")
    @Action(input = "http://publicar.ws/UsuarioWs/verInfoUsuarioRequest", output = "http://publicar.ws/UsuarioWs/verInfoUsuarioResponse", fault = {
        @FaultAction(className = UsuarioNoExisteFault_Exception.class, value = "http://publicar.ws/UsuarioWs/verInfoUsuario/Fault/UsuarioNoExisteFault")
    })
    public DataUsuario verInfoUsuario(
        @WebParam(name = "nickname", targetNamespace = "")
        String nickname)
        throws UsuarioNoExisteFault_Exception
    ;

    /**
     * 
     * @param nickname
     * @return
     *     returns ws.usuarios.DataUsuario
     * @throws UsuarioNoExisteFault_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getOrganizador", targetNamespace = "http://publicar.ws/", className = "ws.usuarios.GetOrganizador")
    @ResponseWrapper(localName = "getOrganizadorResponse", targetNamespace = "http://publicar.ws/", className = "ws.usuarios.GetOrganizadorResponse")
    @Action(input = "http://publicar.ws/UsuarioWs/getOrganizadorRequest", output = "http://publicar.ws/UsuarioWs/getOrganizadorResponse", fault = {
        @FaultAction(className = UsuarioNoExisteFault_Exception.class, value = "http://publicar.ws/UsuarioWs/getOrganizador/Fault/UsuarioNoExisteFault")
    })
    public DataUsuario getOrganizador(
        @WebParam(name = "nickname", targetNamespace = "")
        String nickname)
        throws UsuarioNoExisteFault_Exception
    ;

    /**
     * 
     * @return
     *     returns java.util.List<ws.usuarios.DataUsuario>
     * @throws UsuarioNoExisteFault_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getOrganizadores", targetNamespace = "http://publicar.ws/", className = "ws.usuarios.GetOrganizadores")
    @ResponseWrapper(localName = "getOrganizadoresResponse", targetNamespace = "http://publicar.ws/", className = "ws.usuarios.GetOrganizadoresResponse")
    @Action(input = "http://publicar.ws/UsuarioWs/getOrganizadoresRequest", output = "http://publicar.ws/UsuarioWs/getOrganizadoresResponse", fault = {
        @FaultAction(className = UsuarioNoExisteFault_Exception.class, value = "http://publicar.ws/UsuarioWs/getOrganizadores/Fault/UsuarioNoExisteFault")
    })
    public List<DataUsuario> getOrganizadores()
        throws UsuarioNoExisteFault_Exception
    ;

    /**
     * 
     * @param apellido
     * @param correo
     * @param descripcion
     * @param fechaNac
     * @param imagen
     * @param link
     * @param nickname
     * @param nombre
     * @param password
     * @param tipo
     * @throws UsuarioRepetidoFault_Exception
     */
    @WebMethod
    @RequestWrapper(localName = "altaUsuario", targetNamespace = "http://publicar.ws/", className = "ws.usuarios.AltaUsuario")
    @ResponseWrapper(localName = "altaUsuarioResponse", targetNamespace = "http://publicar.ws/", className = "ws.usuarios.AltaUsuarioResponse")
    @Action(input = "http://publicar.ws/UsuarioWs/altaUsuarioRequest", output = "http://publicar.ws/UsuarioWs/altaUsuarioResponse", fault = {
        @FaultAction(className = UsuarioRepetidoFault_Exception.class, value = "http://publicar.ws/UsuarioWs/altaUsuario/Fault/UsuarioRepetidoFault")
    })
    public void altaUsuario(
        @WebParam(name = "nickname", targetNamespace = "")
        String nickname,
        @WebParam(name = "nombre", targetNamespace = "")
        String nombre,
        @WebParam(name = "correo", targetNamespace = "")
        String correo,
        @WebParam(name = "imagen", targetNamespace = "")
        String imagen,
        @WebParam(name = "password", targetNamespace = "")
        String password,
        @WebParam(name = "tipo", targetNamespace = "")
        String tipo,
        @WebParam(name = "descripcion", targetNamespace = "")
        String descripcion,
        @WebParam(name = "link", targetNamespace = "")
        String link,
        @WebParam(name = "apellido", targetNamespace = "")
        String apellido,
        @WebParam(name = "fechaNac", targetNamespace = "")
        String fechaNac)
        throws UsuarioRepetidoFault_Exception
    ;

}
