
package ws.eventos;

import java.util.List;
import jakarta.jws.WebMethod;
import jakarta.jws.WebResult;
import jakarta.jws.WebService;
import jakarta.xml.bind.annotation.XmlSeeAlso;
import jakarta.xml.ws.Action;
import jakarta.xml.ws.FaultAction;
import jakarta.xml.ws.RequestWrapper;
import jakarta.xml.ws.ResponseWrapper;


/**
 * This class was generated by the XML-WS Tools.
 * XML-WS Tools 4.0.0
 * Generated source version: 3.0
 * 
 */
@WebService(name = "EventosWs", targetNamespace = "http://publicar.wz/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface EventosWs {


    /**
     * 
     * @return
     *     returns java.util.List<ws.eventos.DataEvento>
     * @throws EventoNoExisteFault_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "listarEventoExistentes", targetNamespace = "http://publicar.wz/", className = "ws.eventos.ListarEventoExistentes")
    @ResponseWrapper(localName = "listarEventoExistentesResponse", targetNamespace = "http://publicar.wz/", className = "ws.eventos.ListarEventoExistentesResponse")
    @Action(input = "http://publicar.wz/EventosWs/listarEventoExistentesRequest", output = "http://publicar.wz/EventosWs/listarEventoExistentesResponse", fault = {
        @FaultAction(className = EventoNoExisteFault_Exception.class, value = "http://publicar.wz/EventosWs/listarEventoExistentes/Fault/EventoNoExisteFault")
    })
    public List<DataEvento> listarEventoExistentes()
        throws EventoNoExisteFault_Exception
    ;

}
