
package ws.eventos;

import java.util.List;
import jakarta.jws.WebMethod;
import jakarta.jws.WebParam;
import jakarta.jws.WebResult;
import jakarta.jws.WebService;
import jakarta.xml.bind.annotation.XmlSeeAlso;
import jakarta.xml.ws.Action;
import jakarta.xml.ws.FaultAction;
import jakarta.xml.ws.RequestWrapper;
import jakarta.xml.ws.ResponseWrapper;


/**
 * This class was generated by the XML-WS Tools.
 * XML-WS Tools 4.0.0
 * Generated source version: 3.0
 * 
 */
@WebService(name = "EventosWs", targetNamespace = "http://publicar.ws/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface EventosWs {


    /**
     * 
     * @param nombreEvento
     * @return
     *     returns java.util.List<ws.eventos.DataEdicion>
     * @throws EdicionNoExisteFault_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "listarEdicionesIngresadasEvento", targetNamespace = "http://publicar.ws/", className = "ws.eventos.ListarEdicionesIngresadasEvento")
    @ResponseWrapper(localName = "listarEdicionesIngresadasEventoResponse", targetNamespace = "http://publicar.ws/", className = "ws.eventos.ListarEdicionesIngresadasEventoResponse")
    @Action(input = "http://publicar.ws/EventosWs/listarEdicionesIngresadasEventoRequest", output = "http://publicar.ws/EventosWs/listarEdicionesIngresadasEventoResponse", fault = {
        @FaultAction(className = EdicionNoExisteFault_Exception.class, value = "http://publicar.ws/EventosWs/listarEdicionesIngresadasEvento/Fault/EdicionNoExisteFault")
    })
    public List<DataEdicion> listarEdicionesIngresadasEvento(
        @WebParam(name = "nombreEvento", targetNamespace = "")
        String nombreEvento)
        throws EdicionNoExisteFault_Exception
    ;

    /**
     * 
     * @param nombreEvento
     * @return
     *     returns java.util.List<ws.eventos.DataEdicion>
     * @throws EdicionNoExisteFault_Exception
     * @throws EventoNoExisteFault_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "listarEdicionesAceptadasEvento", targetNamespace = "http://publicar.ws/", className = "ws.eventos.ListarEdicionesAceptadasEvento")
    @ResponseWrapper(localName = "listarEdicionesAceptadasEventoResponse", targetNamespace = "http://publicar.ws/", className = "ws.eventos.ListarEdicionesAceptadasEventoResponse")
    @Action(input = "http://publicar.ws/EventosWs/listarEdicionesAceptadasEventoRequest", output = "http://publicar.ws/EventosWs/listarEdicionesAceptadasEventoResponse", fault = {
        @FaultAction(className = EdicionNoExisteFault_Exception.class, value = "http://publicar.ws/EventosWs/listarEdicionesAceptadasEvento/Fault/EdicionNoExisteFault"),
        @FaultAction(className = EventoNoExisteFault_Exception.class, value = "http://publicar.ws/EventosWs/listarEdicionesAceptadasEvento/Fault/EventoNoExisteFault")
    })
    public List<DataEdicion> listarEdicionesAceptadasEvento(
        @WebParam(name = "nombreEvento", targetNamespace = "")
        String nombreEvento)
        throws EdicionNoExisteFault_Exception, EventoNoExisteFault_Exception
    ;

    /**
     * 
     * @param nombreEvento
     * @return
     *     returns java.util.List<ws.eventos.DataEdicion>
     * @throws EdicionNoExisteFault_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "listarEdicionesRechazadasEvento", targetNamespace = "http://publicar.ws/", className = "ws.eventos.ListarEdicionesRechazadasEvento")
    @ResponseWrapper(localName = "listarEdicionesRechazadasEventoResponse", targetNamespace = "http://publicar.ws/", className = "ws.eventos.ListarEdicionesRechazadasEventoResponse")
    @Action(input = "http://publicar.ws/EventosWs/listarEdicionesRechazadasEventoRequest", output = "http://publicar.ws/EventosWs/listarEdicionesRechazadasEventoResponse", fault = {
        @FaultAction(className = EdicionNoExisteFault_Exception.class, value = "http://publicar.ws/EventosWs/listarEdicionesRechazadasEvento/Fault/EdicionNoExisteFault")
    })
    public List<DataEdicion> listarEdicionesRechazadasEvento(
        @WebParam(name = "nombreEvento", targetNamespace = "")
        String nombreEvento)
        throws EdicionNoExisteFault_Exception
    ;

    /**
     * 
     * @param arg0
     * @param arg1
     * @throws EdicionSinComenzarFault_Exception
     */
    @WebMethod
    @RequestWrapper(localName = "confirmarAsistencia", targetNamespace = "http://publicar.ws/", className = "ws.eventos.ConfirmarAsistencia")
    @ResponseWrapper(localName = "confirmarAsistenciaResponse", targetNamespace = "http://publicar.ws/", className = "ws.eventos.ConfirmarAsistenciaResponse")
    @Action(input = "http://publicar.ws/EventosWs/confirmarAsistenciaRequest", output = "http://publicar.ws/EventosWs/confirmarAsistenciaResponse", fault = {
        @FaultAction(className = EdicionSinComenzarFault_Exception.class, value = "http://publicar.ws/EventosWs/confirmarAsistencia/Fault/EdicionSinComenzarFault")
    })
    public void confirmarAsistencia(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1)
        throws EdicionSinComenzarFault_Exception
    ;

    /**
     * 
     * @param nombreEdicion
     * @return
     *     returns java.util.List<ws.eventos.DataRegistro>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "listarRegistrosDeEdicion", targetNamespace = "http://publicar.ws/", className = "ws.eventos.ListarRegistrosDeEdicion")
    @ResponseWrapper(localName = "listarRegistrosDeEdicionResponse", targetNamespace = "http://publicar.ws/", className = "ws.eventos.ListarRegistrosDeEdicionResponse")
    @Action(input = "http://publicar.ws/EventosWs/listarRegistrosDeEdicionRequest", output = "http://publicar.ws/EventosWs/listarRegistrosDeEdicionResponse")
    public List<DataRegistro> listarRegistrosDeEdicion(
        @WebParam(name = "nombreEdicion", targetNamespace = "")
        String nombreEdicion);

    /**
     * 
     * @param nickname
     * @return
     *     returns java.util.List<ws.eventos.DataRegistro>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "listarRegistrosDeUsuario", targetNamespace = "http://publicar.ws/", className = "ws.eventos.ListarRegistrosDeUsuario")
    @ResponseWrapper(localName = "listarRegistrosDeUsuarioResponse", targetNamespace = "http://publicar.ws/", className = "ws.eventos.ListarRegistrosDeUsuarioResponse")
    @Action(input = "http://publicar.ws/EventosWs/listarRegistrosDeUsuarioRequest", output = "http://publicar.ws/EventosWs/listarRegistrosDeUsuarioResponse")
    public List<DataRegistro> listarRegistrosDeUsuario(
        @WebParam(name = "nickname", targetNamespace = "")
        String nickname);

    /**
     * 
     * @param nombreOrganizador
     * @return
     *     returns java.util.List<ws.eventos.DataEdicion>
     * @throws EdicionNoExisteFault_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "listarEdicionesOrganizador", targetNamespace = "http://publicar.ws/", className = "ws.eventos.ListarEdicionesOrganizador")
    @ResponseWrapper(localName = "listarEdicionesOrganizadorResponse", targetNamespace = "http://publicar.ws/", className = "ws.eventos.ListarEdicionesOrganizadorResponse")
    @Action(input = "http://publicar.ws/EventosWs/listarEdicionesOrganizadorRequest", output = "http://publicar.ws/EventosWs/listarEdicionesOrganizadorResponse", fault = {
        @FaultAction(className = EdicionNoExisteFault_Exception.class, value = "http://publicar.ws/EventosWs/listarEdicionesOrganizador/Fault/EdicionNoExisteFault")
    })
    public List<DataEdicion> listarEdicionesOrganizador(
        @WebParam(name = "nombreOrganizador", targetNamespace = "")
        String nombreOrganizador)
        throws EdicionNoExisteFault_Exception
    ;

    /**
     * 
     * @param nickname
     * @param nombreEdicion
     * @return
     *     returns ws.eventos.DataRegistro
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "listarUnRegistroDeUsuario", targetNamespace = "http://publicar.ws/", className = "ws.eventos.ListarUnRegistroDeUsuario")
    @ResponseWrapper(localName = "listarUnRegistroDeUsuarioResponse", targetNamespace = "http://publicar.ws/", className = "ws.eventos.ListarUnRegistroDeUsuarioResponse")
    @Action(input = "http://publicar.ws/EventosWs/listarUnRegistroDeUsuarioRequest", output = "http://publicar.ws/EventosWs/listarUnRegistroDeUsuarioResponse")
    public DataRegistro listarUnRegistroDeUsuario(
        @WebParam(name = "nombreEdicion", targetNamespace = "")
        String nombreEdicion,
        @WebParam(name = "nickname", targetNamespace = "")
        String nickname);

    /**
     * 
     * @return
     *     returns java.util.List<ws.eventos.DataEdicion>
     * @throws EdicionNoExisteFault_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "listarEdicionesAceptadas", targetNamespace = "http://publicar.ws/", className = "ws.eventos.ListarEdicionesAceptadas")
    @ResponseWrapper(localName = "listarEdicionesAceptadasResponse", targetNamespace = "http://publicar.ws/", className = "ws.eventos.ListarEdicionesAceptadasResponse")
    @Action(input = "http://publicar.ws/EventosWs/listarEdicionesAceptadasRequest", output = "http://publicar.ws/EventosWs/listarEdicionesAceptadasResponse", fault = {
        @FaultAction(className = EdicionNoExisteFault_Exception.class, value = "http://publicar.ws/EventosWs/listarEdicionesAceptadas/Fault/EdicionNoExisteFault")
    })
    public List<DataEdicion> listarEdicionesAceptadas()
        throws EdicionNoExisteFault_Exception
    ;

    /**
     * 
     * @return
     *     returns java.util.List<ws.eventos.DataEdicion>
     * @throws EdicionNoExisteFault_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "listarEdicionesRechazadas", targetNamespace = "http://publicar.ws/", className = "ws.eventos.ListarEdicionesRechazadas")
    @ResponseWrapper(localName = "listarEdicionesRechazadasResponse", targetNamespace = "http://publicar.ws/", className = "ws.eventos.ListarEdicionesRechazadasResponse")
    @Action(input = "http://publicar.ws/EventosWs/listarEdicionesRechazadasRequest", output = "http://publicar.ws/EventosWs/listarEdicionesRechazadasResponse", fault = {
        @FaultAction(className = EdicionNoExisteFault_Exception.class, value = "http://publicar.ws/EventosWs/listarEdicionesRechazadas/Fault/EdicionNoExisteFault")
    })
    public List<DataEdicion> listarEdicionesRechazadas()
        throws EdicionNoExisteFault_Exception
    ;

    /**
     * 
     * @return
     *     returns java.util.List<ws.eventos.DataEvento>
     * @throws EventoNoExisteFault_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "listarEventoExistentes", targetNamespace = "http://publicar.ws/", className = "ws.eventos.ListarEventoExistentes")
    @ResponseWrapper(localName = "listarEventoExistentesResponse", targetNamespace = "http://publicar.ws/", className = "ws.eventos.ListarEventoExistentesResponse")
    @Action(input = "http://publicar.ws/EventosWs/listarEventoExistentesRequest", output = "http://publicar.ws/EventosWs/listarEventoExistentesResponse", fault = {
        @FaultAction(className = EventoNoExisteFault_Exception.class, value = "http://publicar.ws/EventosWs/listarEventoExistentes/Fault/EventoNoExisteFault")
    })
    public List<DataEvento> listarEventoExistentes()
        throws EventoNoExisteFault_Exception
    ;

    /**
     * 
     * @param nombreEdicion
     * @param nombreEvento
     * @return
     *     returns java.util.List<ws.eventos.DataTipoRegistro>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "listarTiposRegistro", targetNamespace = "http://publicar.ws/", className = "ws.eventos.ListarTiposRegistro")
    @ResponseWrapper(localName = "listarTiposRegistroResponse", targetNamespace = "http://publicar.ws/", className = "ws.eventos.ListarTiposRegistroResponse")
    @Action(input = "http://publicar.ws/EventosWs/listarTiposRegistroRequest", output = "http://publicar.ws/EventosWs/listarTiposRegistroResponse")
    public List<DataTipoRegistro> listarTiposRegistro(
        @WebParam(name = "nombreEvento", targetNamespace = "")
        String nombreEvento,
        @WebParam(name = "nombreEdicion", targetNamespace = "")
        String nombreEdicion);

    /**
     * 
     * @param nombreEdicion
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getEventoDeUnaEdicion", targetNamespace = "http://publicar.ws/", className = "ws.eventos.GetEventoDeUnaEdicion")
    @ResponseWrapper(localName = "getEventoDeUnaEdicionResponse", targetNamespace = "http://publicar.ws/", className = "ws.eventos.GetEventoDeUnaEdicionResponse")
    @Action(input = "http://publicar.ws/EventosWs/getEventoDeUnaEdicionRequest", output = "http://publicar.ws/EventosWs/getEventoDeUnaEdicionResponse")
    public String getEventoDeUnaEdicion(
        @WebParam(name = "nombreEdicion", targetNamespace = "")
        String nombreEdicion);

    /**
     * 
     * @return
     *     returns java.util.List<ws.eventos.DataEdicion>
     * @throws EdicionNoExisteFault_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "listarEdicionesIngresadas", targetNamespace = "http://publicar.ws/", className = "ws.eventos.ListarEdicionesIngresadas")
    @ResponseWrapper(localName = "listarEdicionesIngresadasResponse", targetNamespace = "http://publicar.ws/", className = "ws.eventos.ListarEdicionesIngresadasResponse")
    @Action(input = "http://publicar.ws/EventosWs/listarEdicionesIngresadasRequest", output = "http://publicar.ws/EventosWs/listarEdicionesIngresadasResponse", fault = {
        @FaultAction(className = EdicionNoExisteFault_Exception.class, value = "http://publicar.ws/EventosWs/listarEdicionesIngresadas/Fault/EdicionNoExisteFault")
    })
    public List<DataEdicion> listarEdicionesIngresadas()
        throws EdicionNoExisteFault_Exception
    ;

    /**
     * 
     * @param ciudad
     * @param fechaAltaEnPlataforma
     * @param fechaFin
     * @param fechaInicio
     * @param imagen
     * @param nombreEdicion
     * @param nombreEvento
     * @param organizadorNick
     * @param pais
     * @param sigla
     * @param video
     * @throws UsuarioNoExisteFault_Exception
     */
    @WebMethod
    @RequestWrapper(localName = "altaEdicionEvento", targetNamespace = "http://publicar.ws/", className = "ws.eventos.AltaEdicionEvento")
    @ResponseWrapper(localName = "altaEdicionEventoResponse", targetNamespace = "http://publicar.ws/", className = "ws.eventos.AltaEdicionEventoResponse")
    @Action(input = "http://publicar.ws/EventosWs/altaEdicionEventoRequest", output = "http://publicar.ws/EventosWs/altaEdicionEventoResponse", fault = {
        @FaultAction(className = UsuarioNoExisteFault_Exception.class, value = "http://publicar.ws/EventosWs/altaEdicionEvento/Fault/UsuarioNoExisteFault")
    })
    public void altaEdicionEvento(
        @WebParam(name = "nombreEvento", targetNamespace = "")
        String nombreEvento,
        @WebParam(name = "nombreEdicion", targetNamespace = "")
        String nombreEdicion,
        @WebParam(name = "sigla", targetNamespace = "")
        String sigla,
        @WebParam(name = "ciudad", targetNamespace = "")
        String ciudad,
        @WebParam(name = "pais", targetNamespace = "")
        String pais,
        @WebParam(name = "fechaInicio", targetNamespace = "")
        String fechaInicio,
        @WebParam(name = "fechaFin", targetNamespace = "")
        String fechaFin,
        @WebParam(name = "fechaAltaEnPlataforma", targetNamespace = "")
        String fechaAltaEnPlataforma,
        @WebParam(name = "organizadorNick", targetNamespace = "")
        String organizadorNick,
        @WebParam(name = "imagen", targetNamespace = "")
        String imagen,
        @WebParam(name = "video", targetNamespace = "")
        String video)
        throws UsuarioNoExisteFault_Exception
    ;

    /**
     * 
     * @param descripcion
     * @param fechaAltaEnPlataforma
     * @param imagen
     * @param nombre
     * @param nombresCategorias
     * @param sigla
     * @throws EventoRepetidoFault_Exception
     */
    @WebMethod
    @RequestWrapper(localName = "altaEvento", targetNamespace = "http://publicar.ws/", className = "ws.eventos.AltaEvento")
    @ResponseWrapper(localName = "altaEventoResponse", targetNamespace = "http://publicar.ws/", className = "ws.eventos.AltaEventoResponse")
    @Action(input = "http://publicar.ws/EventosWs/altaEventoRequest", output = "http://publicar.ws/EventosWs/altaEventoResponse", fault = {
        @FaultAction(className = EventoRepetidoFault_Exception.class, value = "http://publicar.ws/EventosWs/altaEvento/Fault/EventoRepetidoFault")
    })
    public void altaEvento(
        @WebParam(name = "nombre", targetNamespace = "")
        String nombre,
        @WebParam(name = "descripcion", targetNamespace = "")
        String descripcion,
        @WebParam(name = "sigla", targetNamespace = "")
        String sigla,
        @WebParam(name = "nombresCategorias", targetNamespace = "")
        List<String> nombresCategorias,
        @WebParam(name = "fechaAltaEnPlataforma", targetNamespace = "")
        String fechaAltaEnPlataforma,
        @WebParam(name = "imagen", targetNamespace = "")
        String imagen)
        throws EventoRepetidoFault_Exception
    ;

    /**
     * 
     * @param nombreOrganizador
     * @return
     *     returns java.util.List<ws.eventos.DataEdicion>
     * @throws EdicionNoExisteFault_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "listarEdicionesOrganizadorAceptadas", targetNamespace = "http://publicar.ws/", className = "ws.eventos.ListarEdicionesOrganizadorAceptadas")
    @ResponseWrapper(localName = "listarEdicionesOrganizadorAceptadasResponse", targetNamespace = "http://publicar.ws/", className = "ws.eventos.ListarEdicionesOrganizadorAceptadasResponse")
    @Action(input = "http://publicar.ws/EventosWs/listarEdicionesOrganizadorAceptadasRequest", output = "http://publicar.ws/EventosWs/listarEdicionesOrganizadorAceptadasResponse", fault = {
        @FaultAction(className = EdicionNoExisteFault_Exception.class, value = "http://publicar.ws/EventosWs/listarEdicionesOrganizadorAceptadas/Fault/EdicionNoExisteFault")
    })
    public List<DataEdicion> listarEdicionesOrganizadorAceptadas(
        @WebParam(name = "nombreOrganizador", targetNamespace = "")
        String nombreOrganizador)
        throws EdicionNoExisteFault_Exception
    ;

    /**
     * 
     * @return
     *     returns java.util.List<ws.eventos.DataEvento>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getEventosDTO", targetNamespace = "http://publicar.ws/", className = "ws.eventos.GetEventosDTO")
    @ResponseWrapper(localName = "getEventosDTOResponse", targetNamespace = "http://publicar.ws/", className = "ws.eventos.GetEventosDTOResponse")
    @Action(input = "http://publicar.ws/EventosWs/getEventosDTORequest", output = "http://publicar.ws/EventosWs/getEventosDTOResponse")
    public List<DataEvento> getEventosDTO();

    /**
     * 
     * @param nombre
     * @return
     *     returns ws.eventos.DataEvento
     * @throws EventoNoExisteFault_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getUnEventoDTO", targetNamespace = "http://publicar.ws/", className = "ws.eventos.GetUnEventoDTO")
    @ResponseWrapper(localName = "getUnEventoDTOResponse", targetNamespace = "http://publicar.ws/", className = "ws.eventos.GetUnEventoDTOResponse")
    @Action(input = "http://publicar.ws/EventosWs/getUnEventoDTORequest", output = "http://publicar.ws/EventosWs/getUnEventoDTOResponse", fault = {
        @FaultAction(className = EventoNoExisteFault_Exception.class, value = "http://publicar.ws/EventosWs/getUnEventoDTO/Fault/EventoNoExisteFault")
    })
    public DataEvento getUnEventoDTO(
        @WebParam(name = "nombre", targetNamespace = "")
        String nombre)
        throws EventoNoExisteFault_Exception
    ;

    /**
     * 
     * @param nombreEdicion
     * @param nombreEvento
     * @param nombreTipo
     * @return
     *     returns ws.eventos.DataTipoRegistro
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getTipoRegistro", targetNamespace = "http://publicar.ws/", className = "ws.eventos.GetTipoRegistro")
    @ResponseWrapper(localName = "getTipoRegistroResponse", targetNamespace = "http://publicar.ws/", className = "ws.eventos.GetTipoRegistroResponse")
    @Action(input = "http://publicar.ws/EventosWs/getTipoRegistroRequest", output = "http://publicar.ws/EventosWs/getTipoRegistroResponse")
    public DataTipoRegistro getTipoRegistro(
        @WebParam(name = "nombreEvento", targetNamespace = "")
        String nombreEvento,
        @WebParam(name = "nombreEdicion", targetNamespace = "")
        String nombreEdicion,
        @WebParam(name = "nombreTipo", targetNamespace = "")
        String nombreTipo);

    /**
     * 
     * @param arg0
     * @throws EventoConEdicionesPendientesFault_Exception
     */
    @WebMethod
    @RequestWrapper(localName = "finalizarEvento", targetNamespace = "http://publicar.ws/", className = "ws.eventos.FinalizarEvento")
    @ResponseWrapper(localName = "finalizarEventoResponse", targetNamespace = "http://publicar.ws/", className = "ws.eventos.FinalizarEventoResponse")
    @Action(input = "http://publicar.ws/EventosWs/finalizarEventoRequest", output = "http://publicar.ws/EventosWs/finalizarEventoResponse", fault = {
        @FaultAction(className = EventoConEdicionesPendientesFault_Exception.class, value = "http://publicar.ws/EventosWs/finalizarEvento/Fault/EventoConEdicionesPendientesFault")
    })
    public void finalizarEvento(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0)
        throws EventoConEdicionesPendientesFault_Exception
    ;

    /**
     * 
     * @param nombreEvento
     * @return
     *     returns java.util.List<ws.eventos.DataEdicion>
     * @throws EventoNoExisteFault_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "listarEdiciones", targetNamespace = "http://publicar.ws/", className = "ws.eventos.ListarEdiciones")
    @ResponseWrapper(localName = "listarEdicionesResponse", targetNamespace = "http://publicar.ws/", className = "ws.eventos.ListarEdicionesResponse")
    @Action(input = "http://publicar.ws/EventosWs/listarEdicionesRequest", output = "http://publicar.ws/EventosWs/listarEdicionesResponse", fault = {
        @FaultAction(className = EventoNoExisteFault_Exception.class, value = "http://publicar.ws/EventosWs/listarEdiciones/Fault/EventoNoExisteFault")
    })
    public List<DataEdicion> listarEdiciones(
        @WebParam(name = "nombreEvento", targetNamespace = "")
        String nombreEvento)
        throws EventoNoExisteFault_Exception
    ;

    /**
     * 
     * @param aceptada
     * @param nombreEdicion
     * @throws EdicionNoExisteFault_Exception
     * @throws TransicionEstadoInvalidaFault_Exception
     */
    @WebMethod
    @RequestWrapper(localName = "aceptarEdicion", targetNamespace = "http://publicar.ws/", className = "ws.eventos.AceptarEdicion")
    @ResponseWrapper(localName = "aceptarEdicionResponse", targetNamespace = "http://publicar.ws/", className = "ws.eventos.AceptarEdicionResponse")
    @Action(input = "http://publicar.ws/EventosWs/aceptarEdicionRequest", output = "http://publicar.ws/EventosWs/aceptarEdicionResponse", fault = {
        @FaultAction(className = EdicionNoExisteFault_Exception.class, value = "http://publicar.ws/EventosWs/aceptarEdicion/Fault/EdicionNoExisteFault"),
        @FaultAction(className = TransicionEstadoInvalidaFault_Exception.class, value = "http://publicar.ws/EventosWs/aceptarEdicion/Fault/TransicionEstadoInvalidaFault")
    })
    public void aceptarEdicion(
        @WebParam(name = "nombreEdicion", targetNamespace = "")
        String nombreEdicion,
        @WebParam(name = "aceptada", targetNamespace = "")
        Boolean aceptada)
        throws EdicionNoExisteFault_Exception, TransicionEstadoInvalidaFault_Exception
    ;

    /**
     * 
     * @param idEdicion
     * @return
     *     returns ws.eventos.DataEdicion
     * @throws EdicionNoExisteFault_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getInfoEdicion", targetNamespace = "http://publicar.ws/", className = "ws.eventos.GetInfoEdicion")
    @ResponseWrapper(localName = "getInfoEdicionResponse", targetNamespace = "http://publicar.ws/", className = "ws.eventos.GetInfoEdicionResponse")
    @Action(input = "http://publicar.ws/EventosWs/getInfoEdicionRequest", output = "http://publicar.ws/EventosWs/getInfoEdicionResponse", fault = {
        @FaultAction(className = EdicionNoExisteFault_Exception.class, value = "http://publicar.ws/EventosWs/getInfoEdicion/Fault/EdicionNoExisteFault")
    })
    public DataEdicion getInfoEdicion(
        @WebParam(name = "idEdicion", targetNamespace = "")
        String idEdicion)
        throws EdicionNoExisteFault_Exception
    ;

    /**
     * 
     * @return
     *     returns java.util.List<java.lang.String>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "listarCategorias", targetNamespace = "http://publicar.ws/", className = "ws.eventos.ListarCategorias")
    @ResponseWrapper(localName = "listarCategoriasResponse", targetNamespace = "http://publicar.ws/", className = "ws.eventos.ListarCategoriasResponse")
    @Action(input = "http://publicar.ws/EventosWs/listarCategoriasRequest", output = "http://publicar.ws/EventosWs/listarCategoriasResponse")
    public List<String> listarCategorias();

    /**
     * 
     * @param costo
     * @param cupos
     * @param descripcion
     * @param nombreEdicion
     * @param nombreEvento
     * @param nombreTipoRegistro
     * @throws TipoRegistroRepetidoFault_Exception
     */
    @WebMethod
    @RequestWrapper(localName = "altaTipoRegistro", targetNamespace = "http://publicar.ws/", className = "ws.eventos.AltaTipoRegistro")
    @ResponseWrapper(localName = "altaTipoRegistroResponse", targetNamespace = "http://publicar.ws/", className = "ws.eventos.AltaTipoRegistroResponse")
    @Action(input = "http://publicar.ws/EventosWs/altaTipoRegistroRequest", output = "http://publicar.ws/EventosWs/altaTipoRegistroResponse", fault = {
        @FaultAction(className = TipoRegistroRepetidoFault_Exception.class, value = "http://publicar.ws/EventosWs/altaTipoRegistro/Fault/TipoRegistroRepetidoFault")
    })
    public void altaTipoRegistro(
        @WebParam(name = "nombreEvento", targetNamespace = "")
        String nombreEvento,
        @WebParam(name = "nombreEdicion", targetNamespace = "")
        String nombreEdicion,
        @WebParam(name = "nombreTipoRegistro", targetNamespace = "")
        String nombreTipoRegistro,
        @WebParam(name = "descripcion", targetNamespace = "")
        String descripcion,
        @WebParam(name = "costo", targetNamespace = "")
        Integer costo,
        @WebParam(name = "cupos", targetNamespace = "")
        Integer cupos)
        throws TipoRegistroRepetidoFault_Exception
    ;

    /**
     * 
     * @param fecha
     * @param nombreAsistente
     * @param nombreEdicion
     * @param nombreEvento
     * @param nombreTipoRegistro
     * @throws UsuarioNoExisteFault_Exception
     */
    @WebMethod
    @RequestWrapper(localName = "altaRegistro", targetNamespace = "http://publicar.ws/", className = "ws.eventos.AltaRegistro")
    @ResponseWrapper(localName = "altaRegistroResponse", targetNamespace = "http://publicar.ws/", className = "ws.eventos.AltaRegistroResponse")
    @Action(input = "http://publicar.ws/EventosWs/altaRegistroRequest", output = "http://publicar.ws/EventosWs/altaRegistroResponse", fault = {
        @FaultAction(className = UsuarioNoExisteFault_Exception.class, value = "http://publicar.ws/EventosWs/altaRegistro/Fault/UsuarioNoExisteFault")
    })
    public void altaRegistro(
        @WebParam(name = "nombreEvento", targetNamespace = "")
        String nombreEvento,
        @WebParam(name = "nombreEdicion", targetNamespace = "")
        String nombreEdicion,
        @WebParam(name = "nombreTipoRegistro", targetNamespace = "")
        String nombreTipoRegistro,
        @WebParam(name = "nombreAsistente", targetNamespace = "")
        String nombreAsistente,
        @WebParam(name = "fecha", targetNamespace = "")
        String fecha)
        throws UsuarioNoExisteFault_Exception
    ;

    /**
     * 
     * @param nombre
     * @throws CategoriaRepetidaFault_Exception
     */
    @WebMethod
    @RequestWrapper(localName = "altaCategoria", targetNamespace = "http://publicar.ws/", className = "ws.eventos.AltaCategoria")
    @ResponseWrapper(localName = "altaCategoriaResponse", targetNamespace = "http://publicar.ws/", className = "ws.eventos.AltaCategoriaResponse")
    @Action(input = "http://publicar.ws/EventosWs/altaCategoriaRequest", output = "http://publicar.ws/EventosWs/altaCategoriaResponse", fault = {
        @FaultAction(className = CategoriaRepetidaFault_Exception.class, value = "http://publicar.ws/EventosWs/altaCategoria/Fault/CategoriaRepetidaFault")
    })
    public void altaCategoria(
        @WebParam(name = "nombre", targetNamespace = "")
        String nombre)
        throws CategoriaRepetidaFault_Exception
    ;

    /**
     * 
     * @param edicion
     * @param nickname
     * @param nombreTipo
     * @param precio
     */
    @WebMethod
    @RequestWrapper(localName = "setCostoRegistro", targetNamespace = "http://publicar.ws/", className = "ws.eventos.SetCostoRegistro")
    @ResponseWrapper(localName = "setCostoRegistroResponse", targetNamespace = "http://publicar.ws/", className = "ws.eventos.SetCostoRegistroResponse")
    @Action(input = "http://publicar.ws/EventosWs/setCostoRegistroRequest", output = "http://publicar.ws/EventosWs/setCostoRegistroResponse")
    public void setCostoRegistro(
        @WebParam(name = "nickname", targetNamespace = "")
        String nickname,
        @WebParam(name = "edicion", targetNamespace = "")
        String edicion,
        @WebParam(name = "nombreTipo", targetNamespace = "")
        String nombreTipo,
        @WebParam(name = "precio", targetNamespace = "")
        int precio);

}
