
package ws.eventos;

import jakarta.xml.ws.WebFault;


/**
 * This class was generated by the XML-WS Tools.
 * XML-WS Tools 4.0.0
 * Generated source version: 3.0
 * 
 */
@WebFault(name = "CategoriaRepetidaFault", targetNamespace = "http://publicar.ws/")
public class CategoriaRepetidaFault_Exception
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private CategoriaRepetidaFault faultInfo;

    /**
     * 
     * @param faultInfo
     * @param message
     */
    public CategoriaRepetidaFault_Exception(String message, CategoriaRepetidaFault faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param cause
     * @param faultInfo
     * @param message
     */
    public CategoriaRepetidaFault_Exception(String message, CategoriaRepetidaFault faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: ws.eventos.CategoriaRepetidaFault
     */
    public CategoriaRepetidaFault getFaultInfo() {
        return faultInfo;
    }

}
