
package ws.usuario;

import jakarta.xml.ws.WebFault;


/**
 * This class was generated by the XML-WS Tools.
 * XML-WS Tools 4.0.1
 * Generated source version: 3.0
 * 
 */
@WebFault(name = "EventoRepetidoFault", targetNamespace = "http://publicar.ws/")
public class EventoRepetidoFault_Exception
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private EventoRepetidoFault faultInfo;

    /**
     * 
     * @param faultInfo
     * @param message
     */
    public EventoRepetidoFault_Exception(String message, EventoRepetidoFault faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param cause
     * @param faultInfo
     * @param message
     */
    public EventoRepetidoFault_Exception(String message, EventoRepetidoFault faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: ws.usuario.EventoRepetidoFault
     */
    public EventoRepetidoFault getFaultInfo() {
        return faultInfo;
    }

}
