
package ws.media;

import jakarta.jws.WebMethod;
import jakarta.jws.WebParam;
import jakarta.jws.WebResult;
import jakarta.jws.WebService;
import jakarta.xml.bind.annotation.XmlSeeAlso;
import jakarta.xml.ws.Action;
import jakarta.xml.ws.FaultAction;
import jakarta.xml.ws.RequestWrapper;
import jakarta.xml.ws.ResponseWrapper;


/**
 * This class was generated by the XML-WS Tools.
 * XML-WS Tools 4.0.0
 * Generated source version: 3.0
 * 
 */
@WebService(name = "MediaWs", targetNamespace = "http://publicar.ws/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface MediaWs {


    /**
     * 
     * @param nombreArchivo
     * @return
     *     returns byte[]
     * @throws IOException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "obtenerImagen", targetNamespace = "http://publicar.ws/", className = "ws.media.ObtenerImagen")
    @ResponseWrapper(localName = "obtenerImagenResponse", targetNamespace = "http://publicar.ws/", className = "ws.media.ObtenerImagenResponse")
    @Action(input = "http://publicar.ws/MediaWs/obtenerImagenRequest", output = "http://publicar.ws/MediaWs/obtenerImagenResponse", fault = {
        @FaultAction(className = IOException_Exception.class, value = "http://publicar.ws/MediaWs/obtenerImagen/Fault/IOException")
    })
    public byte[] obtenerImagen(
        @WebParam(name = "nombreArchivo", targetNamespace = "")
        String nombreArchivo)
        throws IOException_Exception
    ;

    /**
     * 
     * @param imagenBytes
     * @param nombreArchivo
     * @return
     *     returns java.lang.String
     * @throws IOException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "subirImagen", targetNamespace = "http://publicar.ws/", className = "ws.media.SubirImagen")
    @ResponseWrapper(localName = "subirImagenResponse", targetNamespace = "http://publicar.ws/", className = "ws.media.SubirImagenResponse")
    @Action(input = "http://publicar.ws/MediaWs/subirImagenRequest", output = "http://publicar.ws/MediaWs/subirImagenResponse", fault = {
        @FaultAction(className = IOException_Exception.class, value = "http://publicar.ws/MediaWs/subirImagen/Fault/IOException")
    })
    public String subirImagen(
        @WebParam(name = "nombreArchivo", targetNamespace = "")
        String nombreArchivo,
        @WebParam(name = "imagenBytes", targetNamespace = "")
        byte[] imagenBytes)
        throws IOException_Exception
    ;

}
