
package ws.media;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import jakarta.xml.ws.Service;
import jakarta.xml.ws.WebEndpoint;
import jakarta.xml.ws.WebServiceClient;
import jakarta.xml.ws.WebServiceException;
import jakarta.xml.ws.WebServiceFeature;


/**
 * This class was generated by the XML-WS Tools.
 * XML-WS Tools 4.0.0
 * Generated source version: 3.0
 * 
 */
@WebServiceClient(name = "MediaService", targetNamespace = "http://publicar.ws/", wsdlLocation = "http://localhost:9128/Servicios/MediaWs?wsdl")
public class MediaService
    extends Service
{

    private final static URL MEDIASERVICE_WSDL_LOCATION;
    private final static WebServiceException MEDIASERVICE_EXCEPTION;
    private final static QName MEDIASERVICE_QNAME = new QName("http://publicar.ws/", "MediaService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:9128/Servicios/MediaWs?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        MEDIASERVICE_WSDL_LOCATION = url;
        MEDIASERVICE_EXCEPTION = e;
    }

    public MediaService() {
        super(__getWsdlLocation(), MEDIASERVICE_QNAME);
    }

    public MediaService(WebServiceFeature... features) {
        super(__getWsdlLocation(), MEDIASERVICE_QNAME, features);
    }

    public MediaService(URL wsdlLocation) {
        super(wsdlLocation, MEDIASERVICE_QNAME);
    }

    public MediaService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, MEDIASERVICE_QNAME, features);
    }

    public MediaService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public MediaService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns MediaWs
     */
    @WebEndpoint(name = "MediaPort")
    public MediaWs getMediaPort() {
        return super.getPort(new QName("http://publicar.ws/", "MediaPort"), MediaWs.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link jakarta.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns MediaWs
     */
    @WebEndpoint(name = "MediaPort")
    public MediaWs getMediaPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://publicar.ws/", "MediaPort"), MediaWs.class, features);
    }

    private static URL __getWsdlLocation() {
        if (MEDIASERVICE_EXCEPTION!= null) {
            throw MEDIASERVICE_EXCEPTION;
        }
        return MEDIASERVICE_WSDL_LOCATION;
    }

}
