
package ws.usuario;

import jakarta.xml.ws.WebFault;


/**
 * This class was generated by the XML-WS Tools.
 * XML-WS Tools 4.0.0
 * Generated source version: 3.0
 * 
 */
@WebFault(name = "PasswordIncorrectaFault", targetNamespace = "http://publicar.ws/")
public class PasswordIncorrectaFault_Exception
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private PasswordIncorrectaFault faultInfo;

    /**
     * 
     * @param faultInfo
     * @param message
     */
    public PasswordIncorrectaFault_Exception(String message, PasswordIncorrectaFault faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param cause
     * @param faultInfo
     * @param message
     */
    public PasswordIncorrectaFault_Exception(String message, PasswordIncorrectaFault faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: ws.usuario.PasswordIncorrectaFault
     */
    public PasswordIncorrectaFault getFaultInfo() {
        return faultInfo;
    }

}
