
package ws.usuario;

import java.io.File;
import java.io.FileInputStream;
import java.net.MalformedURLException;
import java.net.URI;
import java.net.URL;
import java.util.Properties;

import javax.xml.namespace.QName;
import jakarta.xml.ws.Service;
import jakarta.xml.ws.WebEndpoint;
import jakarta.xml.ws.WebServiceClient;
import jakarta.xml.ws.WebServiceException;
import jakarta.xml.ws.WebServiceFeature;


/**
 * This class was generated by the XML-WS Tools.
 * XML-WS Tools 4.0.0
 * Generated source version: 3.0
 * 
 */
@WebServiceClient(name = "UsuarioService", targetNamespace = "http://publicar.ws/", wsdlLocation = "http://localhost:9128/Servicios/UsuariosWS?wsdl")
public class UsuarioService
    extends Service
{

  private static final URL USUARIOSERVICE_WSDL_LOCATION;
  private static final WebServiceException USUARIOSERVICE_EXCEPTION;
  private static final QName USUARIOSERVICE_QNAME = new QName("http://publicar.ws/", "UsuarioService");

  static {
      URL url = null;
      WebServiceException ex = null;
      try {
          String configPath = System.getProperty("user.home")
              + File.separator + ".eventosUy"
              + File.separator + "cliente.properties";

          Properties p = new Properties();
          try (FileInputStream in = new FileInputStream(configPath)) {
              p.load(in);
          }

          String protocol = p.getProperty("Protocol", "http");
          String host     = p.getProperty("Host", "localhost");
          String port     = p.getProperty("Port", "9128");
          String base     = p.getProperty("Base", "/Servicios");

          String baseURL = protocol + "://" + host + ":" + port + base;
          url = URI.create(baseURL + "/UsuariosWS?wsdl").toURL();
      } catch (Exception e0) {
          ex = new WebServiceException(e0);
      }
      USUARIOSERVICE_WSDL_LOCATION = url;
      USUARIOSERVICE_EXCEPTION = ex;
  }

    public UsuarioService() {
        super(__getWsdlLocation(), USUARIOSERVICE_QNAME);
    }

    public UsuarioService(WebServiceFeature... features) {
        super(__getWsdlLocation(), USUARIOSERVICE_QNAME, features);
    }

    public UsuarioService(URL wsdlLocation) {
        super(wsdlLocation, USUARIOSERVICE_QNAME);
    }

    public UsuarioService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, USUARIOSERVICE_QNAME, features);
    }

    public UsuarioService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public UsuarioService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns UsuarioWs
     */
    @WebEndpoint(name = "UsuarioPort")
    public UsuarioWs getUsuarioPort() {
        return super.getPort(new QName("http://publicar.ws/", "UsuarioPort"), UsuarioWs.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link jakarta.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns UsuarioWs
     */
    @WebEndpoint(name = "UsuarioPort")
    public UsuarioWs getUsuarioPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://publicar.ws/", "UsuarioPort"), UsuarioWs.class, features);
    }

    private static URL __getWsdlLocation() {
        if (USUARIOSERVICE_EXCEPTION!= null) {
            throw USUARIOSERVICE_EXCEPTION;
        }
        return USUARIOSERVICE_WSDL_LOCATION;
    }

}
