
package ws.eventos;

import jakarta.xml.ws.WebFault;


/**
 * This class was generated by the XML-WS Tools.
 * XML-WS Tools 4.0.1
 * Generated source version: 3.0
 * 
 */
@WebFault(name = "EventoNoExisteFault", targetNamespace = "http://publicar.ws/")
public class EventoNoExisteFault_Exception
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private EventoNoExisteFault faultInfo;

    /**
     * 
     * @param faultInfo
     * @param message
     */
    public EventoNoExisteFault_Exception(String message, EventoNoExisteFault faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param cause
     * @param faultInfo
     * @param message
     */
    public EventoNoExisteFault_Exception(String message, EventoNoExisteFault faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: ws.eventos.EventoNoExisteFault
     */
    public EventoNoExisteFault getFaultInfo() {
        return faultInfo;
    }

}
