
package ws.eventos;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import jakarta.xml.ws.Service;
import jakarta.xml.ws.WebEndpoint;
import jakarta.xml.ws.WebServiceClient;
import jakarta.xml.ws.WebServiceException;
import jakarta.xml.ws.WebServiceFeature;


/**
 * This class was generated by the XML-WS Tools.
 * XML-WS Tools 4.0.1
 * Generated source version: 3.0
 * 
 */
@WebServiceClient(name = "EventosService", targetNamespace = "http://publicar.ws/", wsdlLocation = "http://localhost:9128/Servicios/EventosWS?wsdl")
public class EventosService
    extends Service
{

    private static final URL EVENTOSSERVICE_WSDL_LOCATION;
    private static final WebServiceException EVENTOSSERVICE_EXCEPTION;
    private static final QName EVENTOSSERVICE_QNAME = new QName("http://publicar.ws/", "EventosService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:9128/Servicios/EventosWS?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        EVENTOSSERVICE_WSDL_LOCATION = url;
        EVENTOSSERVICE_EXCEPTION = e;
    }

    public EventosService() {
        super(__getWsdlLocation(), EVENTOSSERVICE_QNAME);
    }

    public EventosService(WebServiceFeature... features) {
        super(__getWsdlLocation(), EVENTOSSERVICE_QNAME, features);
    }

    public EventosService(URL wsdlLocation) {
        super(wsdlLocation, EVENTOSSERVICE_QNAME);
    }

    public EventosService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, EVENTOSSERVICE_QNAME, features);
    }

    public EventosService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public EventosService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns EventosWs
     */
    @WebEndpoint(name = "EventosPort")
    public EventosWs getEventosPort() {
        return super.getPort(new QName("http://publicar.ws/", "EventosPort"), EventosWs.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link jakarta.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns EventosWs
     */
    @WebEndpoint(name = "EventosPort")
    public EventosWs getEventosPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://publicar.ws/", "EventosPort"), EventosWs.class, features);
    }

    private static URL __getWsdlLocation() {
        if (EVENTOSSERVICE_EXCEPTION!= null) {
            throw EVENTOSSERVICE_EXCEPTION;
        }
        return EVENTOSSERVICE_WSDL_LOCATION;
    }

}
