
package ws.estado;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import jakarta.xml.ws.Service;
import jakarta.xml.ws.WebEndpoint;
import jakarta.xml.ws.WebServiceClient;
import jakarta.xml.ws.WebServiceException;
import jakarta.xml.ws.WebServiceFeature;


/**
 * This class was generated by the XML-WS Tools.
 * XML-WS Tools 4.0.0
 * Generated source version: 3.0
 * 
 */
@WebServiceClient(name = "EstadoService", targetNamespace = "http://publicar.ws/", wsdlLocation = "http://localhost:9128/Servicios/EstadoServidorWS?wsdl")
public class EstadoService
    extends Service
{

    private final static URL ESTADOSERVICE_WSDL_LOCATION;
    private final static WebServiceException ESTADOSERVICE_EXCEPTION;
    private final static QName ESTADOSERVICE_QNAME = new QName("http://publicar.ws/", "EstadoService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:9128/Servicios/EstadoServidorWS?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        ESTADOSERVICE_WSDL_LOCATION = url;
        ESTADOSERVICE_EXCEPTION = e;
    }

    public EstadoService() {
        super(__getWsdlLocation(), ESTADOSERVICE_QNAME);
    }

    public EstadoService(WebServiceFeature... features) {
        super(__getWsdlLocation(), ESTADOSERVICE_QNAME, features);
    }

    public EstadoService(URL wsdlLocation) {
        super(wsdlLocation, ESTADOSERVICE_QNAME);
    }

    public EstadoService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, ESTADOSERVICE_QNAME, features);
    }

    public EstadoService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public EstadoService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns EstadoServidor
     */
    @WebEndpoint(name = "EstadoPort")
    public EstadoServidor getEstadoPort() {
        return super.getPort(new QName("http://publicar.ws/", "EstadoPort"), EstadoServidor.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link jakarta.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns EstadoServidor
     */
    @WebEndpoint(name = "EstadoPort")
    public EstadoServidor getEstadoPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://publicar.ws/", "EstadoPort"), EstadoServidor.class, features);
    }

    private static URL __getWsdlLocation() {
        if (ESTADOSERVICE_EXCEPTION!= null) {
            throw ESTADOSERVICE_EXCEPTION;
        }
        return ESTADOSERVICE_WSDL_LOCATION;
    }

}
