
package ws.estado;

import jakarta.jws.WebMethod;
import jakarta.jws.WebResult;
import jakarta.jws.WebService;
import jakarta.xml.bind.annotation.XmlSeeAlso;
import jakarta.xml.ws.Action;
import jakarta.xml.ws.RequestWrapper;
import jakarta.xml.ws.ResponseWrapper;


/**
 * This class was generated by the XML-WS Tools.
 * XML-WS Tools 4.0.1
 * Generated source version: 3.0
 * 
 */
@WebService(name = "EstadoServidor", targetNamespace = "http://publicar.ws/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface EstadoServidor {


    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getFechaInicio", targetNamespace = "http://publicar.ws/", className = "ws.estado.GetFechaInicio")
    @ResponseWrapper(localName = "getFechaInicioResponse", targetNamespace = "http://publicar.ws/", className = "ws.estado.GetFechaInicioResponse")
    @Action(input = "http://publicar.ws/EstadoServidor/getFechaInicioRequest", output = "http://publicar.ws/EstadoServidor/getFechaInicioResponse")
    public String getFechaInicio();

    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "ping", targetNamespace = "http://publicar.ws/", className = "ws.estado.Ping")
    @ResponseWrapper(localName = "pingResponse", targetNamespace = "http://publicar.ws/", className = "ws.estado.PingResponse")
    @Action(input = "http://publicar.ws/EstadoServidor/pingRequest", output = "http://publicar.ws/EstadoServidor/pingResponse")
    public String ping();

}
