
package ws.estado;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import jakarta.xml.ws.Service;
import jakarta.xml.ws.WebEndpoint;
import jakarta.xml.ws.WebServiceClient;
import jakarta.xml.ws.WebServiceException;
import jakarta.xml.ws.WebServiceFeature;


/**
 * This class was generated by the XML-WS Tools.
 * XML-WS Tools 4.0.1
 * Generated source version: 3.0
 * 
 */
@WebServiceClient(name = "EstadoServidorService", targetNamespace = "http://publicar.ws/", wsdlLocation = "http://localhost:9128/Servicios/EstadoServidorWS?wsdl")
public class EstadoServidorService
    extends Service
{

    private static final URL ESTADOSERVIDORSERVICE_WSDL_LOCATION;
    private static final WebServiceException ESTADOSERVIDORSERVICE_EXCEPTION;
    private static final QName ESTADOSERVIDORSERVICE_QNAME = new QName("http://publicar.ws/", "EstadoServidorService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:9128/Servicios/EstadoServidorWS?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        ESTADOSERVIDORSERVICE_WSDL_LOCATION = url;
        ESTADOSERVIDORSERVICE_EXCEPTION = e;
    }

    public EstadoServidorService() {
        super(__getWsdlLocation(), ESTADOSERVIDORSERVICE_QNAME);
    }

    public EstadoServidorService(WebServiceFeature... features) {
        super(__getWsdlLocation(), ESTADOSERVIDORSERVICE_QNAME, features);
    }

    public EstadoServidorService(URL wsdlLocation) {
        super(wsdlLocation, ESTADOSERVIDORSERVICE_QNAME);
    }

    public EstadoServidorService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, ESTADOSERVIDORSERVICE_QNAME, features);
    }

    public EstadoServidorService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public EstadoServidorService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns EstadoServidor
     */
    @WebEndpoint(name = "EstadoServidorPort")
    public EstadoServidor getEstadoServidorPort() {
        return super.getPort(new QName("http://publicar.ws/", "EstadoServidorPort"), EstadoServidor.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link jakarta.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns EstadoServidor
     */
    @WebEndpoint(name = "EstadoServidorPort")
    public EstadoServidor getEstadoServidorPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://publicar.ws/", "EstadoServidorPort"), EstadoServidor.class, features);
    }

    private static URL __getWsdlLocation() {
        if (ESTADOSERVIDORSERVICE_EXCEPTION!= null) {
            throw ESTADOSERVIDORSERVICE_EXCEPTION;
        }
        return ESTADOSERVIDORSERVICE_WSDL_LOCATION;
    }

}
